# Generated by Django 5.1 on 2025-08-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi_verse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shinobi',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
