# Generated by Django 5.1 on 2025-08-06 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi_verse', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Nickname must be alphanumeric without spaces or special characters', regex='^[A-Za-z0-9]*$')]),
        ),
    ]
