# Generated by Django 5.1 on 2025-08-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi_verse', '0004_alter_profile_bio_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shinobi',
            name='clan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
