# Generated by Django 5.1 on 2025-08-11 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi_verse', '0005_alter_shinobi_clan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shinobi',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shinobis', to=settings.AUTH_USER_MODEL),
        ),
    ]
