# Generated by Django 5.1 on 2025-08-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi_verse', '0006_clan_created_by_shinobi_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
